name: CI for Angular service tests
on: push
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Node Setup
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependecies
        run: npm ci
      - name: Run Tests
        run: npm run test -- --no-watch --code-coverage --browsers=ChromeHeadlessCI
